### ISSUE TITLE
errors after migrating to breeze 2.0.0-alpha

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze-client#12]
After migrating to Angular 8, setting target to es2015 and upgrading to breeze 2.0.0-alpha.12, I'm having these errors :

`import { JsonResultsAdapter, QueryContext, NodeContext, EntityType } from 'breeze-client';`

-> ERROR in src/app/breeze-adapter.ts(1,30): error TS2305: Module '"/angularApp/node_modules/breeze-client/breeze-client"' has no exported member 'QueryContext'.

`  public readonly contractManagementEntityManager: EntityManager = new EntityManager(this._contractManagementManagerOptions); `
-> error TS2693: 'EntityManager' only refers to a type, but is being used as a value here.

`jsonResultsAdapter: new JsonResultsAdapter(BreezeAdapter.dtoAdapter)`
-> jsonResultsAdapter: new JsonResultsAdapter(BreezeAdapter.dtoAdapter)

**Comment by steveschmitt** [comment]
`QueryContext` is now `MappingContext`

I'm not sure about the other errors.

**Comment by graphicsxp** [comment]
Ok, but why are the names changing  ? Is this documented somewhere ? 

I'll try tomorrow. I have many other errors that I haven't listed here yet, will give it another try.

**Comment by graphicsxp** [comment]
Ok, I have replaced QueryContext with MappingContext. But there are so many other errors related to this upgrade. Let's start with this one, when trying to register my Validators : 

`Validator.registerFactory(this.nonDefaultGuidValidator, 'nonDefaultGuidValidator');`

<code>

public nonDefaultGuidValidator(): Validator {
        const name = 'nonGuidIdValidator';
        const context = {
            messageTemplate: 'the %displayName% is required.'
        };

        const validator = new Validator(name, _valFunction, context);

        function _valFunction(value) {
            return value ? value !== DataType.Guid.defaultValue : false;
        }

        return validator;
    }

</code>


now gives the following error : 

`error TS2345: Argument of type '() => Validator' is not assignable to parameter of type 'ValidationFn'.
  Type 'Validator' is not assignable to type 'boolean'.`

**Comment by graphicsxp** [comment]
The error `error TS2693: 'EntityManager' only refers to a type, but is being used as a value here.` went away after I uninstalled package `breeze-client-labs` . I cannot remember why I need it though, it may break at runtime now.

I also have this error : `error TS2693: 'EntityManager' only refers to a type, but is being used as a value here.`  when doing :

`new JsonResultsAdapter(BreezeAdapter.dtoAdapter)`  where dtoAdapter is defined as :

static dtoAdapter = new JsonResultsAdapter( ... )

Of course I realize dtoAdapter should be JsonResultsAdapterConfig but :

1) this works with breeze-client 1.7
2) JsonResultsAdapterConfig  cannot be imported because VSCode don't find it (TypeScript definition missing ?)

**Comment by graphicsxp** [comment]
Another issue :

<code>

      private _contractManagementManagerOptions: EntityManagerOptions = {
    dataService: new DataService({
      serviceName: `${environment.backendUrl}${environment.webApiEndpoint}${environment.contractManagementController}`,
      hasServerMetadata: false,
      adapterName: 'WebApi'
    }),
    metadataStore: new MetadataStore({ namingConvention: NamingConvention.camelCase })
  };

</code>

Now `EntityManagerOptions` is unknown.  It seems I should use `EntityManagerConfig`  instead.

However I can only import `EntityManagerConfig` from 'breeze-client/src/entity-manager'. This should be imported from 'breeze-client'.

**Comment by graphicsxp** [comment]
I also have this error : `error TS2693: 'EntityManager' only refers to a type, but is being used as a value here.`  when doing :

`new JsonResultsAdapter(BreezeAdapter.dtoAdapter)`  where dtoAdapter is defined as :

` static dtoAdapter = new JsonResultsAdapter( ... )`

Of course I realize dtoAdapter should be JsonResultsAdapterConfig but :

1) this works with breeze-client 1.7
2) JsonResultsAdapterConfig  cannot be imported because VSCode don't find it (TypeScript definition missing ?)

**Comment by graphicsxp** [comment]
After commenting problematic code parts (or refactoring where necessary) I've managed to compile for Angular 8 and breeze 2.0 (waiting for the fixes above though).

However, at runtime the application fails to load with the following error : 
` Unregistered adapter.  Interface: modelLibrary AdapterName: backingStore`

I'm using `breeze-bridge2-angular`  and the error is fired when the following code is called :

` config.initializeAdapterInstance('modelLibrary', 'backingStore', true);`

Any idea what to do ?

**Comment by steveschmitt** [comment]
You are right about the missing `EntityManagerConfig` and `JsonResultsAdapterConfig`.  Are there other missing exports that you noticed?

I think we will have to overhaul *breeze-client-labs* to work with Breeze 2.0.  Or maybe move `getEntityGraph` into `breeze-client`.

Please read carefully the Adapter Changes section of the [README](https://github.com/Breeze/breeze-client/blob/master/README.md#adapter-changes).  You should not import the `BreezeBridgeHttpClientModule`, just:

    import { AjaxHttpClientAdapter } from 'breeze-bridge2-angular';

In case it helps, my `tsconfig.json` has this:

    "compilerOptions": {
        "baseUrl": "./src",
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "module": "esnext",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "target": "es2015",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2018",
            "dom"
        ]
    }

**Comment by graphicsxp** [comment]
I have not noticed any other missing exports.

Do you think adding getEntitygraph to breeze-client is something that could be done in the near future ? 

Also, I have follwed the instructions regarding the Adapter changes. But I get a compilation error :

`Unexpected value 'AjaxHttpClientAdapter' imported by the module 'AppModule'. Please add a @NgModule annotation.`

My App module looks similar to this :

    <code>

  @NgModule({  ...   })
    export class AppModule {

  constructor(http: HttpClient) {
    // the order is important
    ModelLibraryBackingStoreAdapter.register();
    UriBuilderODataAdapter.register();

    config.registerAdapter('ajax', <any>function () { return new AjaxHttpClientAdapter(http); });
    config.initializeAdapterInstance('ajax', AjaxHttpClientAdapter.adapterName, true);

    DataServiceWebApiAdapter.register();
  }

     </code> 

I don't see what I'm doing any different from what the documentation says.  Note that I'm using my own breeze-client module (I've added the missing exports) but I don't think that should matters since it is from the latest version. 

Can you add the missing exports and I'll try again with the repo sources ?  Or do you have an idea what this error is about ?

**Comment by steveschmitt** [comment]
I've published breeze-client@2.0.0-alpha.13 with the missing EntityManagerConfig and JsonResultsAdapterConfig.

You _should not_ have `AjaxHttpClientAdapter` in your `imports: [...]` array of the @NgModule

**Comment by graphicsxp** [comment]
Thanks for the new version with the missing exports.

Indeed, you are right, I had added AjaxHttpClientAdapter in my imports. (I had done a 'find and replace' of BreezeBridgeHttpClientModule.... 

Ok, my application is loading and most screens are working. However I still have a few issues but I'll open new issues and close this one for now.
